# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XoIpRG0dvjl6rcoAKhu4GCs3uRefV9UP
"""

import pandas
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

np.random.seed(42)
tf.random.set_seed(42)

from tensorflow.keras.datasets import boston_housing

(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()

print(f"Тренировочных примеров: {train_data.shape[0]}")
print(f"Тестовых примеров: {test_data.shape[0]}")
print(f"Кол-во параметров: {train_data.shape[1]}")

print(f"Данные первого дома: {train_data[0]}")
print(f"Цена первого дома (1000$): {train_targets[0]}")

mean = train_data.mean(axis=0)
print(f"{mean}")

train_data -= mean
print(train_data)

std = train_data.std(axis=0)
print(std)

train_data /= std

print(train_data)

test_data -= mean
test_data /=std

print(f"Данные первого дома: {train_data[0]}")

def build_model():
  model = keras.Sequential([
      layers.Dense(128, activation='relu', input_shape=(train_data.shape[1],)),
      layers.Dense(128, activation='relu'),
      layers.Dense(64, activation='relu'),

      layers.Dense(1)
  ])

  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

model = build_model()
model.summary()

history = model.fit(train_data, train_targets,
                    epochs=200,
                    batch_size=16,
                    validation_split=0.2
                    )

mae_history = history.history['val_mae']
print(f"{mae_history}")

test_mse_score, test_mae_score = model.evaluate(test_data, test_targets)

print(test_mse_score, test_mae_score)

predictions = model.predict(test_data[:20])

train_mean_target = train_targets.mean()
train_std_target = train_targets.std()

predictions_denorm = predictions * train_std_target + train_mean_target

print("Сравнение (в 1000$)")
for i in range (20):
  print(f"прогноз сети: {predictions[i]} | Реальная цена: {test_targets[i]}")

import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({
    'Прогноз сети': predictions.flatten(),
    'Реальная цена': test_targets[:len(predictions)]
})
print(df)

plt.figure(figsize=(10, 6))
plt.plot(df['Прогноз сети'], label='Прогноз сети', marker='o')
plt.plot(df['Реальная цена'], label='Реальная цена', marker='x')
plt.title('Сравнение прогнозов сети и реальных цен')
plt.xlabel('Пример')
plt.ylabel('Цена (в 1000$)')
plt.legend()
plt.grid(True)
plt.show()
